on:
  push:
    branches:
    - release

name: Dist

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - run: cargo build --release --all-features

      - run: cp ./target/release/example ./dist/dist-aarch64-unknown-linux-gnu

      - uses: actions/upload-artifact@v1
        with:
          name: dist-aarch64-unknown-linux-gnu
          path: ./dist